[package]
name = "Muse"
version = "1.5.2"
edition = "2024"

[dependencies]
macroquad = { git = "https://github.com/GpapPeaky/Muse-macroquad", branch = "muse_kill_vsync" }
miniquad = "0.4.8"
once_cell = "1.21.3"
regex = "1.12.2"
rfd = "0.16.0"
