[package]
name = "Muse"
version = "1.5.2"
edition = "2024"

[dependencies]
macroquad = { version = "0.4", features = ["audio"] }
miniquad = "0.4.8"
once_cell = "1.21.3"
regex = "1.12.2"
rfd = "0.16.0"
